# Generated by Django 3.2 on 2021-04-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
