# Generated by Django 3.2 on 2021-04-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_model_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='image',
            field=models.ImageField(default='def_profile.png', upload_to='profiles'),
        ),
    ]
