# Generated by Django 3.2 on 2021-04-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_auto_20210420_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer_model',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
