# Generated by Django 3.2 on 2021-04-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(default='def_report.jpg', upload_to='reports')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile_model')),
            ],
        ),
    ]
