# Generated by Django 3.2 on 2021-04-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_model',
            name='post',
        ),
        migrations.AddField(
            model_name='comment_model',
            name='com_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
