# Generated by Django 3.2 on 2021-04-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210423_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='image',
            field=models.ImageField(default='posts/def_post.jpg', upload_to='posts/'),
        ),
    ]
