# Generated by Django 3.2 on 2021-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userdt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdt_model',
            name='age',
        ),
        migrations.AlterField(
            model_name='userdt_model',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdt_model',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdt_model',
            name='image',
            field=models.ImageField(default='def_profile.png', upload_to='social_profile'),
        ),
        migrations.AlterField(
            model_name='userdt_model',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
