# Generated by Django 3.2 on 2021-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20210428_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdt_model',
            name='bio',
            field=models.TextField(blank=True, max_length=130, null=True),
        ),
    ]
