# Generated by Django 3.2 on 2021-05-14 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0019_messege_model_thread_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_model',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='com_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment_model',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='com_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
