# Generated by Django 3.2 on 2021-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20210514_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdt_model',
            name='image',
            field=models.ImageField(blank=True, default='social_profile/def_profile.png', upload_to='social_profile'),
        ),
    ]
