# Generated by Django 3.2.4 on 2021-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_post_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messege_model',
            old_name='reciever_user',
            new_name='rec',
        ),
        migrations.RenameField(
            model_name='messege_model',
            old_name='senser_user',
            new_name='send',
        ),
        migrations.RemoveField(
            model_name='messege_model',
            name='thread',
        ),
        migrations.DeleteModel(
            name='thread_model',
        ),
    ]
