# Generated by Django 3.2.4 on 2021-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20210630_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege_model',
            name='rec',
        ),
        migrations.AddField(
            model_name='messege_model',
            name='rec_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
