# Generated by Django 3.2.4 on 2021-06-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0024_auto_20210630_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege_model',
            name='rec_id',
        ),
        migrations.AddField(
            model_name='messege_model',
            name='rec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messege_model',
            name='send',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
