# Generated by Django 3.2.4 on 2021-07-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_chat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='room_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
