# Generated by Django 3.2.4 on 2021-07-08 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_chat_model_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='cr_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
