# Generated by Django 3.2.4 on 2021-07-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_remove_messege_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messege_model',
            name='vip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
