# Generated by Django 3.2 on 2021-04-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learncurd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo_model',
            options={'ordering': ['-created']},
        ),
    ]
