# Generated by Django 3.2 on 2021-04-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210420_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, to='sales.Position'),
        ),
    ]
