# Generated by Django 3.2 on 2021-04-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
