# Generated by Django 3.2 on 2021-04-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sales_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
