# Generated by Django 3.2 on 2021-05-01 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sales_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
