# Generated by Django 3.2 on 2021-05-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20210501_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='updated',
        ),
    ]
