# Generated by Django 3.2.4 on 2021-06-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20210629_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='author',
        ),
    ]
